### ISSUE TITLE
Change: 사용 데이터 변경 이슈

### ISSUE THREAD

**Issue by pabaep** [swhCompany/letsgo#6]
일단 데이터를
[기존 : 도서관 / 박물관, 미술관]  에서
[변경 : 도서관 / 휴양림 / 농어촌 체험 마을]  로 변경할 예정

사유 : 박물관, 미술관에 지역 대분류, 중분류 데이터가 없어서 sorting이 어려움

프론트에서 바뀌는 일
[기존 : 타입이 2가지]
[변경 : 타입이 3가지, 1은 도서관 2는 농어촌 3은 휴양림, 이중 3은 대분류만 되므로 3 선택시 중분류 안나오게  하기]

이렇게 입니다. 확인하면 밑에 comment 달아주고 close 하세요
의견 제시 등등 도 코멘트로!

**Comment by yjw226** [comment]
확인완료
