### ISSUE TITLE
Feat: 리스트에 내용이 없을 때의 화면 구성 요망

### ISSUE THREAD

**Issue by pabaep** [swhCompany/letsgo#8]
리스트에 내용이 없을 경우 화면에 내용이 없다는 정보를 띄워주세요!!
아마 따로 응답을 보낼 예정이긴 한데, 일단 이런 경우에 띄울 화면 또는 알림창 또는 문구를 준비해주세요
alert로 띄우는 거 괜찮은 것 같음 쉽고...

**Comment by yjw226** [comment]
네 알겠습니다 - 확인완료
